<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.68.3" />


<title>Violent Video Games: A Simple Regression Analysis - Vincent&#39;s Blog</title>
<meta property="og:title" content="Violent Video Games: A Simple Regression Analysis - Vincent&#39;s Blog">


  <link href='/icon.png' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/icon.png"
         width="50"
         height="50"
         alt="Blog">
  </a>

  <ul class="nav-links">
    
    <li><a href=""></a></li>
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://github.com/vincentle1">GitHub</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">7 min read</span>
    

    <h1 class="article-title">Violent Video Games: A Simple Regression Analysis</h1>

    
    <span class="article-date">2020-04-01</span>
    

    <div class="article-content">
      <p>Note: All source code can be found on <a href="https://github.com/vincentle1/Violent-Video-Game-Data-Analysis">this Github repo</a>.</p>
<h2 id="introduction">Introduction</h2>
<p>In the last post, I explored the <a href="https://vincentle1.netlify.com/post/violent-video-games-literature-review/">existing literature</a> on violent video games and violent crime. If you recall, the studies I shared found that an increase in violent video game sales was associated with a <em>decrease</em> in violent crime.</p>
<p>To see whether these counterintuitive results held up, I ran a quick and dirty <a href="https://www.statisticshowto.com/probability-and-statistics/regression-analysis/find-a-linear-regression-equation/">linear regression</a> with violent video game sales as the predictor variable and the violent crime rate in the US as the outcome variable.</p>
<p>In this post, I&rsquo;ll describe my entire process and share the results.</p>
<h2 id="gathering-and-tidying-the-data">Gathering and Tidying the Data</h2>
<p>So, where did I get the data in the first place?</p>
<p>For violent video game sales, I used <a href="https://www.vgchartz.com/,">https://www.vgchartz.com/,</a> which has tables that list the 100 top-selling video games in the United States by year and genre. I decided to only include games from the action, shooter and fighting genres, in order to ensure I was specifically analyzing violent video games and not video games in general.</p>
<p>For violent crime, I used a table from the <a href="https://www.fbi.gov/services/cjis/ucr">Uniform Crime Reporting Program</a>, a database maintained by the FBI. Violent crime is defined by the FBI as murder/manslaughter, rape, robbery and aggravated assault.</p>
<p>Once I decided where to get the data, I needed to gather it and tidy it into a suitable form for further analysis. I did this in four steps:</p>
<ol>
<li>First, I wrote a webscraper function that automatically pulled the video game sale tables off of <a href="https://www.vgchartz.com/,">https://www.vgchartz.com/,</a> and then filtered them by genre. It allowed me to pull a table from any year I wanted and put that into an R dataframe. Because I&rsquo;m really proud of it, here&rsquo;s the whole function below!</li>
</ol>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(rvest)
</code></pre></div><pre><code>## Loading required package: xml2
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(stringr)
<span style="color:#a6e22e">library</span>(tidyverse)
</code></pre></div><pre><code>## ── Attaching packages ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 1.3.0 ──
</code></pre><pre><code>## ✓ ggplot2 3.3.0     ✓ purrr   0.3.3
## ✓ tibble  2.1.3     ✓ dplyr   0.8.5
## ✓ tidyr   1.0.2     ✓ forcats 0.5.0
## ✓ readr   1.3.1
</code></pre><pre><code>## ── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
## x dplyr::filter()         masks stats::filter()
## x readr::guess_encoding() masks rvest::guess_encoding()
## x dplyr::lag()            masks stats::lag()
## x purrr::pluck()          masks rvest::pluck()
</code></pre><div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">vg_scraper <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">function</span>(year){
<span style="color:#75715e">#Scrape the chart</span>
url <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">paste</span>(<span style="color:#e6db74">&#34;https://www.vgchartz.com/yearly/&#34;</span>, year, <span style="color:#e6db74">&#34;/USA/&#34;</span>, sep <span style="color:#f92672">=</span> <span style="color:#e6db74">&#34;&#34;</span>) 

vg_list <span style="color:#f92672">&lt;-</span> url <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">read_html</span>() <span style="color:#f92672">%&gt;%</span>
<span style="color:#75715e">#html_nodes finds the table by CSS selector.</span>
  <span style="color:#a6e22e">html_nodes</span>(<span style="color:#e6db74">&#39;#chart_body &gt; table&#39;</span>) <span style="color:#f92672">%&gt;%</span>
<span style="color:#75715e">#html_table puts it into a list of tables.</span>
  <span style="color:#a6e22e">html_table</span>(fill <span style="color:#f92672">=</span> <span style="color:#66d9ef">TRUE</span>)

<span style="color:#75715e">#This extracts the table into a final dataframe we can work with.</span>
vg_dataframe <span style="color:#f92672">&lt;-</span> vg_list[[1]]

<span style="color:#75715e">##Clean up the chart</span>

<span style="color:#75715e">#1. Select columns</span>
vg_dataframe <span style="color:#f92672">&lt;-</span> vg_dataframe<span style="color:#a6e22e">[c</span>(<span style="color:#ae81ff">2</span>, <span style="color:#ae81ff">8</span>)]

<span style="color:#75715e">#2. Rename columns</span>
<span style="color:#a6e22e">names</span>(vg_dataframe)[2] <span style="color:#f92672">&lt;-</span> <span style="color:#e6db74">&#34;Yearly_Sales&#34;</span>

<span style="color:#75715e">#3. Remove all rows with NA</span>
vg_dataframe <span style="color:#f92672">&lt;-</span> vg_dataframe <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">filter</span>(<span style="color:#f92672">!</span><span style="color:#a6e22e">is.na</span>(vg_dataframe<span style="color:#f92672">$</span>Yearly_Sales))

<span style="color:#75715e">#4. Remove commas from Yearly_Sales using gsub and convert to numeric</span>
vg_dataframe<span style="color:#f92672">$</span>Yearly_Sales <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">as.numeric</span>(<span style="color:#a6e22e">gsub</span>(<span style="color:#e6db74">&#34;,&#34;</span>, <span style="color:#e6db74">&#34;&#34;</span>, vg_dataframe<span style="color:#f92672">$</span>Yearly_Sales))

<span style="color:#75715e">#5. Filter by genre. Action, shooter and fighting</span>
vg_dataframe <span style="color:#f92672">&lt;-</span> vg_dataframe <span style="color:#f92672">%&gt;%</span>
  <span style="color:#a6e22e">filter</span>(<span style="color:#a6e22e">str_detect</span>(Game, <span style="color:#e6db74">&#34;Action|Shooter|Fighting&#34;</span> ))

<span style="color:#75715e">#6. Return dataframe</span>
vg_dataframe
}
</code></pre></div><p>Here&rsquo;s some sample output from this function. Say I wanted the video game sale data from 2015. I could just type vg_scraper(2015) and get:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">head</span>(<span style="color:#a6e22e">vg_scraper</span>(<span style="color:#ae81ff">2015</span>))
</code></pre></div><pre><code>##                                                                              Game
## 1                              Call of Duty: Black Ops 3 (PS4)Activision, Shooter
## 2                             Call of Duty: Black Ops 3 (XOne)Activision, Shooter
## 3                     Star Wars: Battlefront (2015) (PS4)Electronic Arts, Shooter
## 4                         Halo 5: Guardians (XOne)Microsoft Game Studios, Shooter
## 5 Uncharted: The Nathan Drake Collection (PS4)Sony Computer Entertainment, Action
## 6                    Star Wars: Battlefront (2015) (XOne)Electronic Arts, Shooter
##   Yearly_Sales
## 1      3700540
## 2      3255118
## 3      2352056
## 4      1986935
## 5      1486339
## 6      1462792
</code></pre><ol start="2">
<li>I then wrote a more general function that used the vg_scraper function to combine all the video game sales from 2005-2018 into one simple dataframe. Here&rsquo;s that output.</li>
</ol>
<pre><code>##    year sum_year_sale
## 1  2005       4590918
## 2  2006      12404813
## 3  2007      18365623
## 4  2008      34872965
## 5  2009      36903451
## 6  2010      43923884
## 7  2011      48619875
## 8  2012      47863548
## 9  2013      51609135
## 10 2014      44006645
## 11 2015      43537307
## 12 2016      37788239
## 13 2017      35206500
## 14 2018      48205951
</code></pre><ol start="3">
<li>After this, I extracted the FBI data and cleaned it up. Here&rsquo;s what that looks like.</li>
</ol>
<pre><code>## New names:
## * `` -&gt; ...2
## * `` -&gt; ...3
## * `` -&gt; ...4
## * `` -&gt; ...5
## * `` -&gt; ...6
## * … and 18 more problems
</code></pre><pre><code>## Warning: Must use a character vector as names.
## This warning is displayed once per session.
</code></pre><pre><code>## # A tibble: 6 x 4
##   year  Population1 `Violent\ncrime2` `Violent \ncrime \nrate`
##   &lt;fct&gt;       &lt;dbl&gt;             &lt;dbl&gt;                    &lt;dbl&gt;
## 1 2005    296507061           1390745                     469 
## 2 2006    299398484           1435123                     479.
## 3 2007    301621157           1422970                     472.
## 4 2008    304059724           1394461                     459.
## 5 2009    307006550           1325896                     432.
## 6 2010    309330219           1251248                     404.
</code></pre><ol start="4">
<li>Lastly, I merged the FBI data with the final output of the video game data. Here&rsquo;s the final dataframe, ready for analysis. The &ldquo;sum_year_sale&rdquo; is violent video game sales, &ldquo;population&rdquo; is total US population that year, &ldquo;violent_crime_abs&rdquo; is total violent crime, and &ldquo;violent_crime_rate&rdquo; is violent crime per 100,000 people.</li>
</ol>
<pre><code>## Joining, by = &quot;year&quot;
</code></pre><pre><code>##    year sum_year_sale population violent_crime_abs violent_crime_rate
## 1  2005       4590918  296507061           1390745              469.0
## 2  2006      12404813  299398484           1435123              479.3
## 3  2007      18365623  301621157           1422970              471.8
## 4  2008      34872965  304059724           1394461              458.6
## 5  2009      36903451  307006550           1325896              431.9
## 6  2010      43923884  309330219           1251248              404.5
## 7  2011      48619875  311587816           1206005              387.1
## 8  2012      47863548  313873685           1217057              387.8
## 9  2013      51609135  316497531           1168298              369.1
## 10 2014      44006645  318907401           1153022              361.6
## 11 2015      43537307  320896618           1199310              373.7
## 12 2016      37788239  323405935           1250162              386.6
## 13 2017      35206500  325147121           1247917              383.8
## 14 2018      48205951  327167434           1206836              368.9
</code></pre><h2 id="analysis">Analysis</h2>
<p>Okay, enough background, on to the regression!</p>
<p>I first plotted the data with violent crime rate per 100,000 people on the y-axis and annual violent video game sales per 100,000 people on the x-axis.</p>
<pre><code>## `geom_smooth()` using formula 'y ~ x'
</code></pre><p><!-- raw HTML omitted --></p>
<p>If I had more data points the graph would be cleaner, but I only had access to violent video game sales starting from 2005. Still, this looked like a negative correlation to me! And indeed it was.</p>
<pre><code>## [1] -0.835573
</code></pre><p>So as violent video game sales went up per year, the violent crime rate went down.</p>
<p>Now the question remained: Would this trend be statistically significant? To check this, I ran the regression. Here&rsquo;s the output.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">lm</span>(violent_crime_rate <span style="color:#f92672">~</span> sum_year_rate, vvg_fbi)
<span style="color:#a6e22e">summary</span>(model)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = violent_crime_rate ~ sum_year_rate, data = vvg_fbi)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.266 -20.088   2.984  14.996  48.664 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   501.687520  18.691672  26.840  4.4e-12 ***
## sum_year_rate  -0.008000   0.001518  -5.269 0.000198 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 24.69 on 12 degrees of freedom
## Multiple R-squared:  0.6982,	Adjusted R-squared:  0.673 
## F-statistic: 27.76 on 1 and 12 DF,  p-value: 0.0001982
</code></pre><p>The adjusted R-Squared was 0.673, meaning the model explained 67.3% of the variation. That&rsquo;s pretty substantial.</p>
<p>The F-statistic, and by extension, the regression coefficient for violent video game sales, was statistically significant. Therefore, we can infer that for every additional violent video game sale per 100,000 people, the violent crime rate decreased by -0.008.</p>
<p>So when we put it all together, what do these facts mean?</p>
<p>Well, I have to be careful with the conclusions I draw. Because my model was so simple, we can&rsquo;t really make any causal claims. It&rsquo;s possible that we are just seeing a spurious connection. In fact, it&rsquo;s even possible violent video games <em>do</em> lead to an increase in violent crime, but this effect is dwarfed by larger omitted variables that pulled the violent crime rate down.</p>
<p>However, at bare minimum, I can say that even if violent video game sales lead to an increase in the crime rate, it must be a very small effect indeed.</p>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

